### ISSUE TITLE
jumps on uninitialized values when computing with saturations

### ISSUE THREAD

**Issue by blattms** [OPM/opm-core#868]
During  a debugging session with Norne I stumbled upon a jump depending on uninitialized values (Not sure whether this has any impact, but it is disturbing):
```gdb
0x0000000001740096 in Opm::EPSTransforms::Transform::scaleSatPc (this=0x2e295040, s=2.1511618219927875e-320, s_min=0, s_max=1.0000000000000007)
    at /home/mblatt/src/dune/opm/opm-core/opm/core/props/satfunc/SatFuncSimple.cpp:109
109	        } else if (s<=smin) {
(gdb)(gdb) up
#1  0x000000000131f5af in Opm::SatFuncGwseg<Opm::NonuniformTableLinear<double> >::evalPc<Opm::ExplicitArraysFluidState> (this=0x1f8c82a0, fluidState=..., 
    pc=0xffeffd950, epst=0x2e295040) at /home/mblatt/src/dune/opm/opm-core/opm/core/props/satfunc/SatFuncGwseg.hpp:570
570	            double _sw = epst->wat.scaleSatPc(fluidState.saturation(pos), this->smin_[pos], this->smax_[pos]);
(gdb) p pos
$3 = 0
(gdb) l
565	    void SatFuncGwseg<TableType>::evalPc(const FluidState& fluidState, double* pc, const EPSTransforms* epst) const
566	    {
567	        pc[this->phase_usage.phase_pos[BlackoilPhases::Liquid]] = 0.0;
568	        if (this->phase_usage.phase_used[BlackoilPhases::Aqua]) {
569	            int pos = this->phase_usage.phase_pos[BlackoilPhases::Aqua];
570	            double _sw = epst->wat.scaleSatPc(fluidState.saturation(pos), this->smin_[pos], this->smax_[pos]);
571	            pc[pos] = epst->wat.pcFactor*this->pcow_(_sw);
572	        }
573	        if (this->phase_usage.phase_used[BlackoilPhases::Vapour]) {
574	            int pos = this->phase_usage.phase_pos[BlackoilPhases::Vapour];
(gdb) p *fluidState.saturations_@3
$20 = {2.1511618219927875e-320, 4.6441846602013503e-315, 0}
(gdb) 
#4  0x0000000001306eb6 in Opm::SatFuncMultiplexer::evalPc<Opm::ExplicitArraysFluidState> (this=0x24b1e2c0, fluidState=..., pc=0xffeffd950, epst=0x2e295040)
    at /home/mblatt/src/dune/opm/opm-core/opm/core/props/satfunc/SatFuncMultiplexer.hpp:251
251	    { OPM_MULTIPLEXER_SATFUNC_CALL(satFunc.evalPc(fluidState, pc, epst), OPM_MULTIPLEXER_CONST); }
(gdb) 
#5  0x00000000012fbd9a in Opm::SaturationPropsFromDeck::capPress (this=0x1f318c30, n=1, s=0xffeffd930, cells=0xffeffd97c, pc=0xffeffd950, dpcds=0x0)
    at /home/mblatt/src/dune/opm/opm-core/opm/core/props/satfunc/SaturationPropsFromDeck_impl.hpp:355
355	                   satfunc_[cell_to_func_[cells[i]]].evalPc(fluidState, pc + np*i, &(eps_transf_[cells[i]]));
(gdb) 
#6  0x000000000172411c in Opm::BlackoilPropertiesFromDeck::capPress (this=0xffefff400, n=1, s=0xffeffd930, cells=0xffeffd97c, pc=0xffeffd950, dpcds=0x0)
    at /home/mblatt/src/dune/opm/opm-core/opm/core/props/BlackoilPropertiesFromDeck.cpp:292
292	        satprops_->capPress(n, s, cells, pc, dpcds);
(gdb) up
#7  0x00000000013654c1 in Opm::Equil::phaseSaturations<Dune::CpGrid, Opm::Equil::EquilReg<Opm::Equil::DensityCalculator<Opm::BlackoilPropertiesInterface> >, Opm::RegionMapping<std::__debug::vector<int, std::allocator<int> > >::CellRange> (G=..., reg=..., cells=..., props=..., 
    swat_init=std::__debug::vector of length 44431, capacity 44431 = {...}, phase_pressures=std::__debug::vector of length 3, capacity 3 = {...})
    at /home/mblatt/src/dune/opm/opm-core/opm/core/simulator/initStateEquil_impl.hpp:718
718	                    props.capPress(1, sat, &cell, pc, 0);
(gdb) (gdb) l
713	                    props.capPress(1, sat, &cell, pc, 0);                   
714	                    phase_pressures[oilpos][local_index] = phase_pressures[gaspos][local_index] - pc[gaspos];
715	                }
716	                if (sg < smin[gaspos]+threshold_sat) {
717	                    sat[gaspos] = smin[gaspos];
718	                    props.capPress(1, sat, &cell, pc, 0);
719	                    phase_pressures[gaspos][local_index] = phase_pressures[oilpos][local_index] + pc[gaspos];
720	                }
721	                if (sw < smin[waterpos]+threshold_sat) {
722	                    sat[waterpos] = smin[waterpos];
```
Seems like the Aqua phase is used  and there is no saturation set, but we still compute on it.

**Comment by blattms** [comment]
BTW Happens for other phases , too:
```gdb
0x0000000001740096 in Opm::EPSTransforms::Transform::scaleSatPc (this=0x2e31a030, s=3.5821864438394175e-315, s_min=0, s_max=1.0000000000000007)
    at /home/mblatt/src/dune/opm/opm-core/opm/core/props/satfunc/SatFuncSimple.cpp:109
109	        } else if (s<=smin) {
(gdb) p pos
No symbol "pos" in current context.
(gdb) up
#1  0x000000000131f67d in Opm::SatFuncGwseg<Opm::NonuniformTableLinear<double> >::evalPc<Opm::ExplicitArraysFluidState> (this=0x1f8c82a0, fluidState=..., 
    pc=0xffeffd950, epst=0x2e319f60) at /home/mblatt/src/dune/opm/opm-core/opm/core/props/satfunc/SatFuncGwseg.hpp:575
575	            double _sg = epst->gas.scaleSatPc(fluidState.saturation(pos), this->smin_[pos], this->smax_[pos]);
(gdb) p pos
$1 = 2
(gdb) p *fluidState.saturations_@3
$2 = {1, 4.6441846602013503e-315, 3.5821864438394175e-315}
```

**Comment by bska** [comment]
> but it is disturbing

Yes it is.  On the other hand, following commit a1eb108 (PR #834) we're not actually using these objects anymore.  That's not to say that there aren't any **other** problems here--possibly in a higher-level caller.  If you're able to conduct a similar test in a recent master (might be a bit difficult since requisite module opm-material doesn't build at the moment--see the [Jenkins CI System](https://ci.opm-project.org/)), then that would be very useful information.

**Comment by andlaus** [comment]
The opm-material build issue was a problem that only appeared with Dune < 2.4. the latest opm-material master should now build on Dune 2.3 again.

**Comment by blattms** [comment]
Great!
